apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: jnyznsfyw-java-springboot
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: rhtap-quay-quay-rhtap-quay.apps.rosa.kx-80b021abb3.clc8.p3.openshiftapps.com/rhtap/rhtap-qe:9072465e3fc2999c9685796017798ab4d3a3509d@sha256:bda0b6f712ef7d99792d5debb9f0da0b9d8887f665728c106dd0bd2f210fc9bf
          name: container-image
